version: '3.5'
services:
  api1:
    image: eufountai/rinha-de-backend
    hostname: api1
    expose:
      - '80'
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
    volumes:
      - .:/app_directory
    environment:
      PORT: 80
      DATABASE_URL: postgres://myuser:mypassword@database:5432/mydatabase
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_HOST: database
      REDIS_PORT: 6379
      REDIS_HOST: redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.7GB'

  api2:
    image: eufountai/rinha-de-backend
    hostname: api2
    expose:
      - '80'
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
    volumes:
      - .:/app_directory
    environment:
      PORT: 80
      DATABASE_URL: postgres://myuser:mypassword@database:5432/mydatabase
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_HOST: database
      REDIS_PORT: 6379
      REDIS_HOST: redis
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.7GB'

  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.3GB'

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.4GB'

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.9GB'