version: "3.5"

services:
  api1:
    image: ghcr.io/vimsos/rinha-backend:main
    hostname: api1
    environment:
      PORT: 8000
      DATABASE_URL: postgres://pg:pg@pg/rinha
    depends_on:
      - pg
    expose:
      - 8000
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.25GB"

  api2:
    image: ghcr.io/vimsos/rinha-backend:main
    hostname: api2
    environment:
      PORT: 8000
      DATABASE_URL: postgres://pg:pg@pg/rinha
    depends_on:
      - pg
    expose:
      - 8000
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.25GB"

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1GB"

  pg:
    image: postgres:16beta3-bookworm
    volumes:
      - ./config/migrations:/docker-entrypoint-initdb.d
    command: postgres -c log_min_messages=FATAL
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: rinha
    ports:
      - "5432"
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "1.5GB"
