version: "3.9"
#IMPORTANTE: Você terá 1.5 CPUs e 3.0GB
services:
  cache:
    image: quay.io/infinispan/server-native:14.0.14.Final
    ports:
      - "11222:11222"
    environment:
      USER: quarkus
      PASS: quarkus
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '256MB'
    healthcheck:
      test: curl -o /dev/null -s --retry 0 --head http://localhost:11222 || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  api1:
    image: quay.io/vflorent/rinha-2023-q3
    environment:
      DB_HOST: db
      QUARKUS_LOG_CONSOLE_ENABLE: "false"
      QUARKUS_LOG_FILE_ENABLE: "false"
      QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE: 30
      QUARKUS_VERTX_EVENT_LOOPS_POOL_SIZE: 30
      QUARKUS_VERTX_WORKER_POOL_SIZE: 5
      QUARKUS_DATASOURCE_REACTIVE_CACHE_PREPARED_STATEMENTS: "true"
    depends_on:
      - db
      - cache
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '500MB'
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000
    healthcheck:
      test: curl -o /dev/null -s --retry 0 --head http://localhost:8080/contagem-pessoas || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  api2:
    image: quay.io/vflorent/rinha-2023-q3
    environment:
      DB_HOST: db
      QUARKUS_LOG_CONSOLE_ENABLE: "false"
      QUARKUS_LOG_FILE_ENABLE: "false"
      QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE: 30
      QUARKUS_VERTX_EVENT_LOOPS_POOL_SIZE: 30
      QUARKUS_VERTX_WORKER_POOL_SIZE: 5
      QUARKUS_DATASOURCE_REACTIVE_CACHE_PREPARED_STATEMENTS: "true"
    depends_on:
      - db
      - cache
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '500MB'
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000
    healthcheck:
      test: curl -o /dev/null -s --retry 0 --head http://localhost:8080/contagem-pessoas || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  nginx:
    image: nginx:1.25.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '256MB'

  db:
    image: postgres:15.4
    command: postgres -c 'max_connections=80' -c 'shared_buffers=512MB' -c 'fsync=off' -c 'max_prepared_transactions=80' -c 'effective_cache_size=512MB' -c 'synchronous_commit=off' -c 'checkpoint_timeout=1d' -c 'max_wal_size=1GB'
    volumes:
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: quarkus
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '2.0GB'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
