version: '3.9'

services:
  api1: &api
    image: leandronsp/rinha-backend-bash
    container_name: api1
    depends_on:
      - postgres
      - pgbouncer
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'

  api2: 
    <<: *api
    container_name: api2

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '0.5GB'

  pgbouncer:
    image: pgbouncer/pgbouncer
    hostname: pgbouncer
    container_name: pgbouncer
    environment:
      - DATABASES_HOST=postgres
      - DATABASES_PORT=5432
      - DATABASES_USER=postgres
      - DATABASES_PASSWORD=postgres
      - DATABASES_DBNAME=postgres
      - DATABASES_POOL_SIZE=20
      - PGBOUNCER_MAX_CLIENT_CONN=100
      - PGBOUNCER_RESERVE_POOL_SIZE=50
      - PGBOUNCER_DEFAULT_POOL_SIZE=50
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'

  nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.3GB'
