version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.6GB'
    networks:
      - app_network      

  api1:
    image: lucasmnribeiro/rinha-bun
    hostname: api1
    depends_on:
      - redis
      - postgres
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.6GB'

  api2:
    image: lucasmnribeiro/rinha-bun
    hostname: api2
    depends_on:
      - redis
      - postgres
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.6GB'

  postgres:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_LOG_STATEMENT: all
      POSTGRES_LOG_DIRECTORY: /var/log/postgresql/
    volumes: 
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.8GB'

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - cache:/data  
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.6GB'

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  postgres_logs:
  cache: