version: '3.5'
services:
  api1: # API - Inst√¢ncia 01
    image: lazaronixon/rinha-de-backend
    hostname: api1
    depends_on:
      - db
    expose:
      - '3000'
    ports:
      - '9999:3000'
    environment:
      RAILS_LOG_LEVEL: error
      DATABASE_URL: postgres://postgres:password@db:5432/rinha_de_backend
      RAILS_MASTER_KEY: d2066c69964ffb8b091dfddc61f42880
      RUBY_YJIT_ENABLE: 1
    deploy:
      resources:
        limits:
          cpus: '1.2'
          memory: '2.0GB'

  db: # Banco de dados
   image: postgres
   command: postgres -c log_min_messages=FATAL
   environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
   deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '1.0GB'

  db-migrator: # Database preparation
    image: lazaronixon/rinha-de-backend
    command: bin/wait-for db:5432 -- bin/rails db:prepare
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/rinha_de_backend
      RAILS_MASTER_KEY: d2066c69964ffb8b091dfddc61f42880
