version: '3.9'

services:

    #api1
    api-01:
        container_name: rinha-backend-api-01
        image: lauroappelt/rinhabackend2023q3:2.1
        networks:
            - rinha
        depends_on:
            - db
            - nginx
            - redis
        command: bash -c "php bin/hyperf.php server:watch"
        deploy:
            resources:
                limits:
                    cpus: '0.35'
                    memory: '0.5GB'

    #api1
    api-02:
        container_name: rinha-backend-api-02
        image: lauroappelt/rinhabackend2023q3:2.1
        networks:
            - rinha
        depends_on:
            - db
            - nginx
            - redis
            - api-01
        command: bash -c "php bin/hyperf.php server:watch"
        deploy:
            resources:
                limits:
                    cpus: '0.35'
                    memory: '0.5GB'

    # postgres
    db:
        container_name: rinha-backend-db
        image: postgres:15.4
        environment:
            POSTGRES_DB: rinha-backend-db
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: rinha
            PGDATA: /var/lib/postgresql/data/db-files/
        volumes:
            - pg_data:/var/lib/postgresql/data
            - ./docker/postgres/postgres.conf:/etc/postgresql.conf
            - ./docker/postgres/db.sql:/docker-entrypoint-initdb.d/db.sql
        command: 'postgres -c config_file="/etc/postgresql.conf"'
        networks:
            - rinha
        deploy:
            resources:
                limits:
                    cpus: '0.65'
                    memory: '0.7GB'

  # nginx
    nginx:
        container_name: rinha-backend-nginx
        image: nginx:alpine
        ports:
            - "9999:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - rinha
        deploy:
            resources:
                limits:
                    cpus: '0.1'
                    memory: '0.2GB'

    # redis
    redis:
        container_name: rinha-backend-redis
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - rinha
        deploy:
            resources:
                limits:
                    cpus: '0.05'
                    memory: '0.2GB'

volumes:
    pg_data:
        driver: local

networks:
    rinha:
        driver: bridge